# Generated by Django 4.2.7 on 2026-03-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='scheduled', max_length=20),
        ),
    ]
